language: node_js
node_js: stable

# 只监听 source 分支的改动
branches:
  only:
  - master

# 缓存依赖，节省持续集成时间
cache:
  directories:
    - node_modules

before_install:
  - git config --global user.name "ryan"
  - git config --global user.email "ryanlid@live.com"
  - chmod +x .travis/deploy.sh

install:
  - npm install

script:
  - npm run generate

after_success:
  - .travis/deploy.sh
